run:
  timeout: 5m
  go: '1.23'

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - nolintlint

linters-settings:
  errcheck:
    check-blank: false
    ignore: fmt:.*,io:Copy,io:ReadAll
  govet:
    enable:
      - shadow
      - unusedresult
    disable:
      - fieldalignment
      - unusedwrite
  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: true

issues:
  exclude-use-default: true
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - linters:
        - unused
      text: "is unused"
  max-issues-per-linter: 0
  max-same-issues: 0
