run:
  timeout: 5m
  go: '1.23'

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - nolintlint

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
